### ISSUE TITLE
Issue with dataExplore/util.py/colorscale

### ISSUE THREAD

**Issue by chrispikula** [dmnfarrell/pandastable#100]
Hi!
colorscale sometimes returns invalid colors, I think, when the (hex) function returns multiple zeros in leading numbers.  I caused this issue by coloring the second column of a table with light green from 'pick a color', and then immediately got the following traceback:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Python\Python\DataExplore\pandastable\core.py", line 510, in setColumnColors
    self.redraw()
  File "C:\Python\Python\DataExplore\pandastable\core.py", line 464, in redraw
    self.redrawVisible(event, callback)
  File "C:\Python\Python\DataExplore\pandastable\core.py", line 455, in redrawVisible
    self.drawMultipleRows(self.multiplerowlist)
  File "C:\Python\Python\DataExplore\pandastable\core.py", line 3345, in drawMultipleRows
    tag=('multiplesel','rowrect'))
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 2498, in create_rectangle
    return self._create('rectangle', args, kw)
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 2477, in _create
    *(args + self._options(cnf, kw))))
_tkinter.TclError: invalid color name "#0e162"

Here is my naïve suggestion on how to fix said issue:

    def colorScale(hex_color, brightness_offset=1):
        """ takes a color like #87c95f and produces a lighter or darker variant """

    #if not hex_color.startswith('#'):
        #import matplotlib
        #hex_color = matplotlib.colors.cnames[hex_color].lower()
    if len(hex_color) != 7:
        raise Exception("Passed %s into color_variant(), needs to be in #87c95f format." % hex_color)
    rgb_hex = [hex_color[x:x+2] for x in [1, 3, 5]]
    new_rgb_int = [int(hex_value, 16) + brightness_offset for hex_value in rgb_hex]
    new_rgb_int = [min([255, max([0, i])]) for i in new_rgb_int]
    # hex() produces "0x88", we want just "88"
    result = "#" + "".join([hex(i)[2:] for i in new_rgb_int])
    # fix solution:
    while len(result) < 7:
        result = result[0] + '0' + result[1:]
    return result

It seems to stop the problem, however it is kind of a hack-ish workaround.

**Comment by dmnfarrell** [comment]
I fixed this by changing the last line to create the proper hex code.

`r,g,b = [min([255, max([1, i])]) for i in new_rgb_int]`
