### ISSUE TITLE
pandastable crashes with UTF-8 decode error

### ISSUE THREAD

**Issue by rpgoldman** [dmnfarrell/pandastable#104]
I have been trying to explore a data table, and when I try to do a scatterplot, I can set the first group by, but when I set the second pandastable crashes with the following error:
```
$ dataexplore 
objc[40395]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff94c77cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x13513bcd8). One of the two will be used. Which one is undefined.
/Users/rpg/Library/Python/3.6/lib/python/site-packages/pandastable/dialogs.py:481: DtypeWarning: Columns (3,4,5,8,10) have mixed types. Specify dtype option on import or set low_memory=False.
  self.main.wait_window()
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/Users/rpg/Library/Python/3.6/lib/python/site-packages/pandastable/headers.py", line 269, in handle_right_click
    self.rightmenu = self.popupMenu(event)
  File "/Users/rpg/Library/Python/3.6/lib/python/site-packages/pandastable/headers.py", line 445, in popupMenu
    popupmenu.post(event.x_root, event.y_root)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 2943, in post
    self.tk.call(self._w, 'post', x, y)
_tkinter.TclError
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/Users/rpg/Library/Python/3.6/lib/python/site-packages/pandastable/headers.py", line 269, in handle_right_click
    self.rightmenu = self.popupMenu(event)
  File "/Users/rpg/Library/Python/3.6/lib/python/site-packages/pandastable/headers.py", line 445, in popupMenu
    popupmenu.post(event.x_root, event.y_root)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 2943, in post
    self.tk.call(self._w, 'post', x, y)
_tkinter.TclError
Traceback (most recent call last):
  File "/Users/rpg/Library/Python/3.6/bin/dataexplore", line 11, in <module>
    sys.exit(main())
  File "/Users/rpg/Library/Python/3.6/lib/python/site-packages/pandastable/app.py", line 1200, in main
    app.mainloop()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1280, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
I *believe* that this is an error that happens when pandastable is processing an event out of the "Group by 2" popup menu, judging from the backtrace.
I couldn't trace this much farther, because I seem to be in callback hell.

**Comment by rpgoldman** [comment]
Should have mentioned: This is on Mac OS 10.13.6, python 3.6.
Had the problem with another pulldown, so I think it might just be Tkinter being bad on this platform.

**Comment by rpgoldman** [comment]
OK, this is what's wrong: https://github.com/nltk/nltk/issues/1673
