### ISSUE TITLE
handle_mouse_drag color error

### ISSUE THREAD

**Issue by arbitrager44** [dmnfarrell/pandastable#114]
Getting the following error when I try to highlight a set of cells:

>Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\arbit\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\arbit\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandastable\core.py", line 2202, in handle_mouse_drag
    self.drawMultipleRows(self.multiplerowlist)
  File "C:\Users\arbit\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandastable\core.py", line 3248, in drawMultipleRows
    clr = util.colorScale(clr, -30)
  File "C:\Users\arbit\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandastable\util.py", line 136, in colorScale
    raise Exception("Passed %s into color_variant(), needs to be in #87c95f format." % hex_color)
Exception: Passed white into color_variant(), needs to be in #87c95f format.

I have an override of `handle_left_click` which could be causing the problem but I can't figure out how:

```
def handle_left_click(self, event):
        super().handle_left_click(event)
        #Check lock
        col = self.get_col_clicked(event)
        row = self.get_row_clicked(event)
        editable_cols = ['Trans par', 'Notes', 'Out_flow', 'Other_rest']
        colindex = ui_df.columns[col]
        if colindex in editable_cols:
            if colindex == 'Trans par':
                self.model.deleteCells(row, col)
            self.drawCellEntry(self.currentrow, self.currentcol)
```

All this is meant to do is make data entry easier in these four columns. I've looked at the code for `handle_mouse_drag` but don't see how I'm mucking it up. Any ideas?

**Comment by arbitrager44** [comment]
Solved my own problem. I had a column coded to be 'white' but was using the English coding method. Looks like `pt.rowcolors` wants to be all in hex codes. I made that change and it solved it.
