### ISSUE TITLE
table does not show any data

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#128]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1544, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/pandastable/headers.py", line 322, in handle_mouse_move
    if x > self.tablewidth+w:
AttributeError: ColumnHeader instance has no attribute 'tablewidth'

**Comment by gsudhanshu** [comment]
problem solved, sorry
