### ISSUE TITLE
table.movetoSelection() produces error

### ISSUE THREAD

**Issue by CypressA** [dmnfarrell/pandastable#153]
I am trying to draw a table with initial focus on a specific row by using table.movetoSelection()
```
from tkinter import *
from pandastable import Table, TableModel
class TestApp(Frame):
        """Basic test frame for the table"""
        def __init__(self, parent=None):
            self.parent = parent
            Frame.__init__(self)
            self.main = self.master
            self.main.geometry('600x400+200+100')
            self.main.title('Table app')
            f = Frame(self.main)
            f.pack(fill=BOTH,expand=1)
            df = TableModel.getSampleData()
            self.table = pt = Table(f, dataframe=df,
                                    showtoolbar=True, showstatusbar=True)
            pt.show()
            pt.movetoSelection(row = 23, col=1) ##
            return
app = TestApp()
app.mainloop()
```
which produces the error
```
Traceback (most recent call last):
  File "C:\Users\svobodov\Desktop\data\tests\print_df_in_window\2. pandastable\0.2 return marked lines\test.py", line 21, in <module>
    app = TestApp()
  File "C:\Users\svobodov\Desktop\data\tests\print_df_in_window\2. pandastable\0.2 return marked lines\test.py", line 18, in __init__
    pt.movetoSelection(row = 23, col=1)
  File "C:\Python35\lib\site-packages\pandastable\core.py", line 2397, in movetoSelection
    self.drawSelectedRow()
  File "C:\Python35\lib\site-packages\pandastable\core.py", line 3297, in drawSelectedRow
    x1,y1,x2,y2 = self.getCellCoords(row,0)
  File "C:\Python35\lib\site-packages\pandastable\core.py", line 2067, in getCellCoords
    x1=self.col_positions[col]
IndexError: list index out of range
```

Is this behaviour expected? Is it normal that `self.col_positions` is empty? Perhaps I am not using the method properly?

**Comment by dmnfarrell** [comment]
It shouldn't be empty but seems to be even after you call show(). You can get around it by calling `pt.redraw()` once before the function.

**Comment by CypressA** [comment]
This patch works, thanks for your answer.
