### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#155]
I receive following error when trying to run my application without sudo 

Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from pandastable import Table
  File "/usr/local/lib/python2.7/dist-packages/pandastable/__init__.py", line 5, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/dist-packages/pandastable/core.py", line 62, in <module>
    logging.basicConfig(filename=logfile,format='%(asctime)s %(message)s')
  File "/usr/lib/python2.7/logging/__init__.py", line 1554, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/sudhanshu/.pandastable/error.log'

**Comment by dmnfarrell** [comment]
You should have write access to the log file if it's in your home directory.

**Comment by gsudhanshu** [comment]
Dear Damien,

what is the location of log file?

The application runs with sudo.. but that should not be a prerequisite

Thanks & Regards,
Sudhanshu Garg
+919811436616

**Comment by dmnfarrell** [comment]
It's in the error message. /home/sudhanshu/.pandastable/error.log
Check your permissions for the folder maybe. Do not run with sudo if u can avoid.

**Comment by gsudhanshu** [comment]
Thanks Damien for your patience.

sudo chmod -R 0777 .
worked for me

Thanks & Regards,
Sudhanshu Garg
+919811436616
