### ISSUE TITLE
Some trouble about self.tablewidth

### ISSUE THREAD

**Issue by lizhendong128** [dmnfarrell/pandastable#170]
When I use pandastable, I get this trouble. Though the data is shown, I want to know what happen.
> Here is the ERROR information:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandastable\headers.py", line 327, in handle_mouse_move
    if x > self.tablewidth+w:
AttributeError: 'ColumnHeader' object has no attribute 'tablewidth'
```

**Comment by lizhendong128** [comment]
I solve this problem just now. The question I submit is not accurate. When I use a function to create the Table and show it, the visible table is blank and if I move the mouse above the index of columns, the ERROR occur. Only if I roll my mouse wheel, the content appears.

I add the `redraw()` after `show()`, the problem is solved.
