### ISSUE TITLE
Error when importing pandastable: OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Se7enSquared** [dmnfarrell/pandastable#200]
**Here's the code that causes this:**

`from pandastable import *`

Windows 10
Visual Studio Code
Python 3.9 Windows Store version
Also installed: pandas, matplotlib, numpy, numexpr

**full Traceback error from python:**
```
[Running] python -u "c:\Users\Heather\Documents\Code\tkinter_practice\tkinter_teest.py"
Traceback (most recent call last):
  File "c:\Users\Heather\Documents\Code\tkinter_practice\tkinter_teest.py", line 3, in <module>
    from pandastable import *
  File "C:\Users\Heather\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandastable\__init__.py", line 5, in <module>
    from .core import *
  File "C:\Users\Heather\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandastable\core.py", line 40, in <module>
    import numpy as np
  File "C:\Users\Heather\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\__init__.py", line 148, in <module>
    from . import _distributor_init
  File "C:\Users\Heather\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 applicatio
```n

**Comment by dmnfarrell** [comment]
This looks like a numpy import issue? Try import numpy and see if it works.
