### ISSUE TITLE
Exception when hovering a mouse over empty table

### ISSUE THREAD

**Issue by GBR-613** [dmnfarrell/pandastable#207]
This is the message:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Programs\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\Programs\Python37\lib\site-packages\pandastable\headers.py", line 327, in handle_mouse_move
    if x > self.tablewidth+w:
AttributeError: 'ColumnHeader' object has no attribute 'tablewidth'
```

**Comment by dmnfarrell** [comment]
should be fixed
