### ISSUE TITLE
AttributeError: 'Table' object has no attribute 'tablecolheader'

### ISSUE THREAD

**Issue by Ismael-VC** [dmnfarrell/pandastable#42]
I get this error with this script:

```python
from tkinter import Tk, Frame, mainloop
from pandastable import Table


def main():
    root = Tk()
    frame = Frame(root)
           
    table = Table(frame)
    table.importCSV("pacientes.csv")
    table.show()
    #table.redraw()

    mainloop()

        
if __name__ == '__main__':
    main()

```

```python
runfile('C:/Users/personal/Documents/Python Scripts/pacientes.py', wdir='C:/Users/personal/Documents/Python Scripts/Pacientes')
Traceback (most recent call last):

  File "<ipython-input-2-0da4d8efad79>", line 1, in <module>
    runfile('C:/Users/personal/Documents/Python Scripts/pacientes.py', wdir='C:/Users/personal/Documents/Python Scripts/Pacientes')

  File "C:\Users\personal\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\personal\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/personal/Documents/Python Scripts/pacientes.py", line 18, in <module>
    main()

  File "C:/Users/personal/Documents/Python Scripts/pacientes.py", line 10, in main
    table.importCSV("pacientes.csv")

  File "C:\Users\personal\Anaconda3\lib\site-packages\pandastable\core.py", line 2907, in importCSV
    self.updateModel(model)

  File "C:\Users\personal\Anaconda3\lib\site-packages\pandastable\core.py", line 2822, in updateModel
    self.tablecolheader.destroy()

AttributeError: 'Table' object has no attribute 'tablecolheader'
```

**Comment by dmnfarrell** [comment]
This is really an error in your code. You did not call frame.pack() to add the frame to the parent first. I've changed updateModel so it checks to see of the colheader exists, and it will just fail silently in this case. table.show() will also have no effect unless the parent frame is visible!

**Comment by Ismael-VC** [comment]
@dmnfarrell thanks for your comment, I'm not very used to `tkinter` yet, I've made a hello world example at #45.
