### ISSUE TITLE
Throws "truth value of a DataFrame is ambiguous" error

### ISSUE THREAD

**Issue by sdsawtelle** [dmnfarrell/pandastable#52]
Using python 3.5 on Windows 10
After successfully running `pip install pandastable`

In IPython shell I do (per the example):
`import pandas as pd
from tkinter import *
from pandastable import Table

data = {
    'A': [10, 11, 12],
    'B': [20, 21, 22],
    'C': ['Peter Pan', 'Cpt. Hook', 'Tinkerbell']
}
df = pd.DataFrame(data)
pt = Table(df)
pt.show()`

The error trace is:

Traceback (most recent call last):
  File "C:\Users\Sonya\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-8f8885a22d0e>", line 1, in <module>
    pt = Table(df)
  File "C:\Users\Sonya\Anaconda3\lib\site-packages\pandastable\core.py", line 58, in __init__
    scrollregion=(0,0,300,200))
  File "C:\Users\Sonya\Anaconda3\lib\tkinter\__init__.py", line 2244, in __init__
    Widget.__init__(self, master, 'canvas', cnf, kw)
  File "C:\Users\Sonya\Anaconda3\lib\tkinter\__init__.py", line 2131, in __init__
    BaseWidget._setup(self, master, cnf)
  File "C:\Users\Sonya\Anaconda3\lib\tkinter\__init__.py", line 2104, in _setup
    if not master:
  File "C:\Users\Sonya\Anaconda3\lib\site-packages\pandas\core\generic.py", line 731, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by dmnfarrell** [comment]
The code for creating the Table is wrong. If you type help(Table) in ipython it will show you that you need to provide a parent frame (this is what it thinks df is in your example).
You should create the widget frame and then call Table(frame, dataframe=df)

see https://github.com/dmnfarrell/pandastable/wiki/Code-Examples

**Comment by sdsawtelle** [comment]
oh was reading too carelessly, thank you very much!
