### ISSUE TITLE
Apply function : value_counts fails

### ISSUE THREAD

**Issue by cgclark** [dmnfarrell/pandastable#82]
**I get the following message when trying to perform the value_counts function on a given column:**

values
[True, False, False, None, True]
['checkbutton', 'checkbutton', 'checkbutton', 'string', 'checkbutton']
{'normalize': 0, 'ascending': 0, 'dropna': 1, 'bins': None, 'sort': 1}
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/xxxxx/anaconda3/lib/python3.5/tkinter/__init__.py", line 1558, in __call__
    return self.func(*args)
  File "/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandastable/core.py", line 1266, in applyFunction
    new = self._callFunction(df[cols], funcname)
  File "/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandastable/core.py", line 1370, in _callFunction
    new = df.apply(func, **p)
  File "/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 4854, in f
    return func(x, *args, **kwds)
  File "/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandas/core/algorithms.py", line 559, in value_counts
    result = result.sort_values(ascending=ascending)
  File "/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandas/core/series.py", line 1913, in sort_values
    raise ValueError('ascending must be boolean')
ValueError: ('ascending must be boolean', 'occurred at index survived')

**I am not sure if this is related: Dataexplore message when launched on a mac (appears to be otherwise successful in launching):**

/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandastable/plotting.py:1558: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.
  canvas.show()
/Users/xxxxx/anaconda3/lib/python3.5/site-packages/pandastable/plotting.py:1562: MatplotlibDeprecationWarning: The NavigationToolbar2TkAgg class was deprecated in version 2.2.
  toolbar = NavigationToolbar2TkAgg(canvas, parent)

**Comment by dmnfarrell** [comment]
value counts is now moved to it's own col header menu item so it probably fixes this. the other message is unrelated but shouldn't appear now either.

**Comment by cgclark** [comment]
**errors when launching dataexplore 0.9.0 on a mac.**

/Users/cgclark/anaconda3/lib/python3.5/site-packages/pandastable/__init__.py:5: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'MacOSX' by the following code:
  File "/Users/xxxx/anaconda3/bin/dataexplore", line 7, in <module>
    from pandastable.app import main
  File "/Users/xxxx/anaconda3/lib/python3.5/site-packages/pandastable/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/xxxx/anaconda3/lib/python3.5/site-packages/pandastable/core.py", line 42, in <module>
    from .plotting import MPLBaseOptions, PlotViewer
  File "/Users/xxxx/anaconda3/lib/python3.5/site-packages/pandastable/plotting.py", line 36, in <module>
    import matplotlib.pyplot as plt
  File "/Users/xxxx/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/Users/xxxx/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('TkAgg')

**This appears to be related to a matplotlib backend warning.
https://github.com/mtazzari/uvplot/issues/14**

**in order to get dataexplore to launch, .../pandastable/__init__.py was modified by inserting the first two lines:**

_import matplotlib
matplotlib.use('TkAgg')_
from .core import *
from .data import *
__version__ = '0.9.0'

**Comment by dmnfarrell** [comment]
Ok I'll add code checking this for mac in __init__.py.
